### ISSUE TITLE
If extension not specified in import, cannot jump to .jsx definition

### ISSUE THREAD

**Issue by valpinkman** [alexheyd/atom-jump-to-import#13]
If the extension is not specified on the import
```js
import Component from 'path/to/component'; // component.jsx
```
when I jump to import on it, it opens a blank *component.js* file (although it doesn't exist)

**Comment by alexheyd** [comment]
I'll take a look thanks for reporting.

**Comment by valpilgrim** [comment]
👍

**Comment by valpinkman** [comment]
👍

**Comment by alexheyd** [comment]
@valpinkman Could you provide some details (OS, package version, package settings)? I'm unable to reproduce.

In the package settings, there's a comma-separated list of accepted File Extensions the package will attempt to open. Is `jsx` listed there? It's part of the default values.

**Comment by valpinkman** [comment]
Oh wow, actually it's not from you pakage. I'm very sorry, using the shortcut works. I thought it was coming from jump-to-import but I use js-hyperclick tu trigger the shortcut... I guess it's from their side. 
Again sorry, your package works perfectly
