### ISSUE TITLE
Don't open folder/index.js

### ISSUE THREAD

**Issue by dmytro-lymarenko** [alexheyd/atom-jump-to-import#17]
It doesn't open a file if the file has name index.js and the import contains only the folder:
`import something from './something'; // doesn't work :(`
`import something from './something/index' // work!!!`

**Comment by dmytro-lymarenko** [comment]
version of the module: 3.3.1
version of atom: 1.13.1 (x64)

**Comment by alexheyd** [comment]
That's not a feature that's supported and isn't planned to be.

**Comment by alexheyd** [comment]
This was added after all: https://github.com/alexheyd/atom-jump-to-import/pull/25
