### ISSUE TITLE
Feature request: Babel module resolver support

### ISSUE THREAD

**Issue by subblue** [alexheyd/atom-jump-to-import#2]
Thanks for releasing this, I was excited to find it and it could prove to be very useful.

One thing I've found handy with the related [autocomplete-modules](https://atom.io/packages/autocomplete-modules) plugin is support for the [babel-plugin-module-resolover](https://github.com/tleunen/babel-plugin-module-resolver) plugin, which is essential for keeping sane import paths with large applications.

I don't know if similar support would be reasonable to add for this plugin?

**Comment by alexheyd** [comment]
That seems like a good idea. This if my first Atom package, so I haven't tried pulling in config from other plugins, but this should be doable. I'll look into how `autocomplete-modules` does it and see if I can add it.

**Comment by alexheyd** [comment]
@subblue I've added support for `babel-plugin-module-resolver` however I don't use this plugin myself. If you run into issues please let me know, thanks!
