### ISSUE TITLE
Support for index file

### ISSUE THREAD

**Issue by nerdchacha** [alexheyd/atom-jump-to-import#24]
Really appreciate the work you have put in to get this module out.
Would it be possible to also add support for `index` files when using directory names in require statements?

For instance 
`import Foo from 'src/components/Foo'` should first look for `src/components/Foo.{extension}` but should also resolve `src/components/Foo/index.{extension}` if the above file is not present

**Comment by alexheyd** [comment]
Added in v3.5.0: https://github.com/alexheyd/atom-jump-to-import/releases/tag/v3.5.0

**Comment by nerdchacha** [comment]
Doesn't work with `Import Paths Aliases` ?

**Comment by alexheyd** [comment]
@nerdchacha could you elaborate? Just tested it and it's working as intended for me, i have an alias of `$PROJECT:app` and `import foo from 'my-project/foo';` opened `/app/foo/index.js`

**Comment by nerdchacha** [comment]
@alexheyd I am running things through webpack and have a resolver set to `src`
i have set the alias as `components:src/components`
I am able to navigate to `import foo from 'components/foo'` (where foo is `foo.js`)
but `import foo from 'components/foo'` doesn't work (where foo is `foo/index.js`)

**Comment by alexheyd** [comment]
Haven't tested things with `webpack` yet. Will be adding support in the near future: https://github.com/alexheyd/atom-jump-to-import/issues/26

**Comment by nerdchacha** [comment]
Having the support to automatically read `resolve` path from webpack would be really cool but with the existing setup, things should still work right?
I only mentioned webpack because the paths in my files are relative to `src`, so instead of writing 
`import foo from 'src/components/foo'`
i just write 
`import foo from 'components/foo'`

and since i have an option to define aliases as `components:src/components`, things should still work with the current version but they don't.

Am i missing something?

does alias support deep paths like `src/components` ?

**Comment by alexheyd** [comment]
Can you confirm that you're on v3.5.0? I just tested with your same setup, and it worked for me:
Alias: `components:src/components`
`import foo from 'components/foo';` -> opened `/components/foo/index.js`

If you are on v3.5.0, could you try in a new project without `webpack`?

**Comment by nerdchacha** [comment]
Works now with a package rebuild.
Thanks for the support mate.
:+1: 
cheers!

**Comment by alexheyd** [comment]
Glad to hear, you're welcome.
