### ISSUE TITLE
Unable to jump-to-import when import has a period in the name (editor.page.js)

### ISSUE THREAD

**Issue by smccarthy** [alexheyd/atom-jump-to-import#31]
<img width="689" alt="screen shot 2017-11-08 at 9 43 15 am" src="https://user-images.githubusercontent.com/4777452/32563781-5fdc1f6e-c46f-11e7-8d25-8058084b5fcf.png">

**Comment by smccarthy** [comment]
The path is missing the final `.js`

**Comment by alexheyd** [comment]
Thanks for the report, will look into this.

**Comment by smccarthy** [comment]
I have a fix and submitting a PR in a few.

**Comment by smccarthy** [comment]
https://github.com/alexheyd/atom-jump-to-import/pull/32

**Comment by smccarthy** [comment]
https://github.com/alexheyd/atom-jump-to-import/pull/32

**Comment by alexheyd** [comment]
https://github.com/alexheyd/atom-jump-to-import/pull/32

**Comment by smccarthy** [comment]
Thanks !

**Comment by alexheyd** [comment]
Thanks for the contribution!
