### ISSUE TITLE
Only works when files are in the same directory

### ISSUE THREAD

**Issue by muxcmux** [alexheyd/atom-jump-to-import#6]
Hi, I had this package installed for quite a long time but recently noticed that it has stopped working for files that are referenced in a directory that is up the tree, for example the following would work ok: (this is an Ember project I'm working on):

```javascript
// app/components/my-component.js
import myMixin from './my-mixin.js';
```

while this will open a blank file and point to the wrong path, although the file exists:

```javascript
// app/components/my-component.js
import myMixin from '../mixins/my-mixin.js';
```

In the latter case it would look for a file `my-mixin.js`, but in a directory that is the parent of my projects' root.

I tried using absolute paths, or changing the path, but then pressing the key combination doesn't do anything.

I tried fiddling around with path overrides in the config, but it looks quite complicated. Can you perhaps point me to the right direction on how to fix this (hopefully it's a config somewhere).

Thanks!

**Comment by alexheyd** [comment]
Thanks for the report, I'll look into this shortly. As for the configuration, are you using `ember-cli` or just Ember by itself? If you left everything at default it should be configured for `ember-cli` projects, as that's what I work with currently. I likely broke something related to opening relative file paths in the latest update.

**Comment by alexheyd** [comment]
Fixed here: https://github.com/alexheyd/atom-jump-to-import/commit/823fc568cf344a402898d1ec3c9713880fc1835f

If you update to `1.8.1` relative paths should work. As for absolute paths, they depend on `ember-cli` magic paths, using a project name defined in a `package.json`. Is your project set up differently?

**Comment by muxcmux** [comment]
Yes, I'm using `ember-cli` and settings are at their defaults. I only tried absolute paths because I couldn't get the relative paths to work, but with this update everything is working like before.

Thank you!
