### ISSUE TITLE
Jump to .jsx files

### ISSUE THREAD

**Issue by subblue** [alexheyd/atom-jump-to-import#7]
For React users it would be super useful to be able to jump to .jsx files as well as .js
I'm not sure if this would require the full multi-extension feature or could work from a smaller .js* type match?

**Comment by alexheyd** [comment]
Just pushed a new update, if you go to the Package Settings you can now configure a list of file extensions to try and open. It defaults to `js` and `jsx` so after updating you should be good to go!
