### ISSUE TITLE
Jump to module from node_modules doesn't work

### ISSUE THREAD

**Issue by dmytro-lymarenko** [alexheyd/atom-jump-to-import#8]
Version of atom: 1.13.1
Version of atom-jump-to-import: 2.1.1

I tried to put my cursor on variable and file name but nothing happens after I press CTRL+ALT+E:
1) import Re|act from 'react';
2) import React from 're|act';
| - is my cursor :)

**Comment by alexheyd** [comment]
It doesn't support that currently. There's no actual path for it to open. The recent support for npm modules that was added is only when used with something like `browserify` and the import path is formatted like `npm:foo`

Come to think of it, I could make `node_modules` the default location checked if it's not a full path.

**Comment by alexheyd** [comment]
Support for jumping to `npm` modules has been added.
